[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/orders"
  to = "/.netlify/functions/orders"
  status = 200

[[redirects]]
  from = "/api/bestsellers"
  to = "/.netlify/functions/bestsellers"
  status = 200
